### ISSUE TITLE
The open source code.

### ISSUE THREAD

**Issue by yueliu1999** [devvrit/S3GC#1]
Congratulations for your NeurIPS 2022 paper 'S3GC: Scalable Self-Supervised Graph Clustering'. Great work! Could you open the source code of the proposed method? Thanks.

**Comment by devvrit** [comment]
Hi,
Thanks for your interest in our work 😄 
We're still working to make it a bit more clean. But till then you can access the code here: https://drive.google.com/corp/drive/folders/18B_eWbdVhOURZhqwoBSsyryb4WsiYLQK
